/**
 * Turret code generator — assembles Move source files from chip selections.
 *
 * The generator produces:
 *   Move.toml              — package manifest with world dependency
 *   sources/turret.move    — the targeting extension with chip snippets injected
 *
 * This generator is Turret-specific, but follows a pattern that Gate/SSU
 * generators can mirror: skeleton + per-chip snippet injection.
 */

import type { FileMap } from '../types';
import type { ChipSelection } from '../chip-types';
import { TURRET_CHIPS } from './chips';

const DEFAULT_MODULE = 'smart_turret_extension';

function replaceModuleName(source: string, moduleName: string): string {
  if (moduleName === DEFAULT_MODULE) return source;
  return source.replaceAll(DEFAULT_MODULE, moduleName);
}

// ---------------------------------------------------------------------------
// Move.toml
// ---------------------------------------------------------------------------

function generateMoveToml(moduleName: string): string {
  return `[package]
name = "${moduleName}"
edition = "2024"

[dependencies]
world = { git = "https://github.com/evefrontier/world-contracts.git", subdir = "contracts/world", rev = "v0.0.21" }

[environments]
testnet = "4c78adac"
testnet_internal = "4c78adac"
testnet_utopia = "4c78adac"
testnet_stillness = "4c78adac"
`;
}

// ---------------------------------------------------------------------------
// sources/turret.move
// ---------------------------------------------------------------------------

function collectSnippets(
  category: string,
  selection: ChipSelection,
): string {
  const enabled = TURRET_CHIPS.filter(
    c => c.category === category && selection.enabledChips.includes(c.id),
  );
  if (enabled.length === 0) return '';

  return enabled
    .map(chip => {
      const params = selection.chipConfigs[chip.id];
      return chip.codeSnippet(params);
    })
    .join('\n');
}

function generateTurretMove(
  moduleName: string,
  selection: ChipSelection,
): string {
  const excludeSnippets = collectSnippets('exclude', selection);
  const weightSnippets = collectSnippets('weight', selection);

  const hasWeightChips = weightSnippets.trim().length > 0;

  return replaceModuleName(
    `/// Turret Targeting Extension — generated by EasyAssemblies.
///
/// Chips: [${selection.enabledChips.join(', ')}]
module smart_turret_extension::turret;

use sui::bcs;
use world::{
    character::{Self, Character},
    turret::{Self, Turret, OnlineReceipt},
};

#[error(code = 0)]
const EInvalidReceipt: vector<u8> = b"OnlineReceipt does not match turret";

public struct TurretAuth has drop {}

public fun get_target_priority_list(
    turret: &Turret,
    owner_character: &Character,
    target_candidate_list: vector<u8>,
    receipt: OnlineReceipt,
): vector<u8> {
    assert!(receipt.turret_id() == object::id(turret), EInvalidReceipt);

    let candidates = turret::unpack_candidate_list(target_candidate_list);
    let owner_character_id = character::key(owner_character).item_id() as u32;
    let owner_tribe = character::tribe(owner_character);

    let mut return_list = vector::empty<turret::ReturnTargetPriorityList>();

    let mut i = 0u64;
    let len = candidates.length();
    while (i < len) {
        let candidate = &candidates[i];
        let mut weight = turret::priority_weight(candidate);
        let mut excluded = false;

        // ═══════════ Exclude chips ═══════════${excludeSnippets || `
        // (none selected)`}

        if (!excluded) {
            // ═══════════ Weight chips ═══════════${weightSnippets || `
            // (none selected)`}

            return_list.push_back(
                turret::new_return_target_priority_list(turret::item_id(candidate), weight),
            );
        };

        i = i + 1;
    };

    turret::destroy_online_receipt(receipt, TurretAuth {});
    bcs::to_bytes(&return_list)
}
`,
    moduleName,
  );
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export interface TurretGeneratorInput {
  moduleName?: string;
  selection: ChipSelection;
}

export function generateTurretFiles(input: TurretGeneratorInput): FileMap {
  const moduleName = input.moduleName || DEFAULT_MODULE;

  return {
    'Move.toml': generateMoveToml(moduleName),
    'sources/turret.move': generateTurretMove(moduleName, input.selection),
  };
}
