/**
 * SSU code generator — assembles Move source files from template + chip selections.
 *
 * Produces:
 *   Move.toml              — package manifest
 *   sources/config.move    — shared ExtensionConfig + AdminCap + XAuth (all templates)
 *   sources/<main>.move    — template-specific main module with chip code injected
 */

import type { FileMap } from '../types';
import type { ChipSelection } from '../chip-types';
import { SSU_CHIPS } from './chips';

const DEFAULT_MODULE = 'smart_storage_unit_extension';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function replaceModuleName(source: string, moduleName: string): string {
  if (moduleName === DEFAULT_MODULE) return source;
  return source.replaceAll(DEFAULT_MODULE, moduleName);
}

function collectSnippets(category: string, selection: ChipSelection): string {
  const enabled = SSU_CHIPS.filter(
    c => c.category === category && selection.enabledChips.includes(c.id),
  );
  if (enabled.length === 0) return '';
  return enabled
    .map(chip => chip.codeSnippet(selection.chipConfigs[chip.id]))
    .join('\n');
}

function hasChip(id: string, selection: ChipSelection): boolean {
  return selection.enabledChips.includes(id);
}

// ---------------------------------------------------------------------------
// Move.toml
// ---------------------------------------------------------------------------

function generateMoveToml(moduleName: string): string {
  return `[package]
name = "${moduleName}"
edition = "2024"

[dependencies]
world = { git = "https://github.com/evefrontier/world-contracts.git", subdir = "contracts/world", rev = "v0.0.21" }

[environments]
testnet = "4c78adac"
testnet_internal = "4c78adac"
testnet_utopia = "4c78adac"
testnet_stillness = "4c78adac"
`;
}

// ---------------------------------------------------------------------------
// sources/config.move  (shared by all SSU templates)
// ---------------------------------------------------------------------------

function generateConfigMove(): string {
  return `/// Shared configuration for SSU extensions — generated by EasyAssemblies.
module smart_storage_unit_extension::config;

use sui::dynamic_field as df;

public struct ExtensionConfig has key {
    id: UID,
}

public struct AdminCap has key, store {
    id: UID,
}

public struct XAuth has drop {}

fun init(ctx: &mut TxContext) {
    let admin_cap = AdminCap { id: object::new(ctx) };
    transfer::transfer(admin_cap, ctx.sender());

    let config = ExtensionConfig { id: object::new(ctx) };
    transfer::share_object(config);
}

public fun has_rule<K: copy + drop + store>(config: &ExtensionConfig, key: K): bool {
    df::exists_(&config.id, key)
}

public fun borrow_rule<K: copy + drop + store, V: store>(config: &ExtensionConfig, key: K): &V {
    df::borrow(&config.id, key)
}

public fun set_rule<K: copy + drop + store, V: store + drop>(
    config: &mut ExtensionConfig,
    _: &AdminCap,
    key: K,
    value: V,
) {
    if (df::exists_(&config.id, copy key)) {
        let _old: V = df::remove(&mut config.id, copy key);
    };
    df::add(&mut config.id, key, value);
}

public fun remove_rule<K: copy + drop + store, V: store>(
    config: &mut ExtensionConfig,
    _: &AdminCap,
    key: K,
): V {
    df::remove(&mut config.id, key)
}

/// Package-visible flag writer — used by airdrop claim-once tracking.
public(package) fun set_flag<K: copy + drop + store>(config: &mut ExtensionConfig, key: K) {
    if (!df::exists_(&config.id, copy key)) {
        df::add(&mut config.id, key, true);
    };
}

public(package) fun x_auth(): XAuth {
    XAuth {}
}
`;
}

// ---------------------------------------------------------------------------
// Template E: Open Storage  (simplest — no chips)
// ---------------------------------------------------------------------------

function generateOpenStorageMove(): string {
  return `/// Open Storage — generated by EasyAssemblies.
///
/// Unrestricted shared warehouse. Anyone can deposit to and withdraw from the
/// open inventory via this extension's witness type.
module smart_storage_unit_extension::open_storage;

use smart_storage_unit_extension::config::{Self, XAuth};
use world::{character::Character, inventory::Item, storage_unit::StorageUnit};

/// Deposit an item into the SSU's open inventory.
/// The caller obtains \`item\` from a preceding \`withdraw_by_owner\` in the PTB.
public fun open_deposit(
    storage_unit: &mut StorageUnit,
    character: &Character,
    item: Item,
    ctx: &mut TxContext,
) {
    storage_unit.deposit_to_open_inventory<XAuth>(character, item, config::x_auth(), ctx);
}

/// Withdraw an item from the SSU's open inventory.
/// The caller should \`deposit_by_owner\` the returned Item in the same PTB.
public fun open_withdraw(
    storage_unit: &mut StorageUnit,
    character: &Character,
    type_id: u64,
    quantity: u32,
    ctx: &mut TxContext,
): Item {
    storage_unit.withdraw_from_open_inventory<XAuth>(character, config::x_auth(), type_id, quantity, ctx)
}
`;
}

// ---------------------------------------------------------------------------
// Template C: Gated Locker
// ---------------------------------------------------------------------------

function generateGatedLockerMove(selection: ChipSelection): string {
  const accessSnippets = collectSnippets('access', selection);
  const itemSnippets = collectSnippets('item', selection);
  const depositOnly = hasChip('I2', selection);

  const depositOnlyGuard = depositOnly
    ? `
    // [I2] Deposit Only — withdrawals are blocked
    abort EWithdrawNotAllowed`
    : '';

  return `/// Gated Locker — generated by EasyAssemblies.
///
/// A shared warehouse with access restrictions. Players deposit to / withdraw
/// from the open inventory, gated by tribe and item-type checks.
/// Chips: [${selection.enabledChips.join(', ')}]
#[allow(unused_use, unused_variable)]
module smart_storage_unit_extension::locker;

use smart_storage_unit_extension::config::{Self, XAuth, ExtensionConfig};
use world::{access::OwnerCap, character::Character, storage_unit::StorageUnit};

// === Errors ===
#[error(code = 0)]
const ENotAllowedTribe: vector<u8> = b"Character tribe not allowed";
#[error(code = 1)]
const EBlockedTribe: vector<u8> = b"Character tribe is blocked";
#[error(code = 2)]
const EItemTypeNotAllowed: vector<u8> = b"Item type not allowed";
#[error(code = 3)]
const EWithdrawNotAllowed: vector<u8> = b"Withdrawals are not allowed";

/// Deposit items from the caller's owned inventory into the shared open inventory.
public fun guarded_deposit<T: key>(
    extension_config: &ExtensionConfig,
    storage_unit: &mut StorageUnit,
    character: &Character,
    owner_cap: &OwnerCap<T>,
    item_type_id: u64,
    quantity: u32,
    ctx: &mut TxContext,
) {
    // ═══════════ Access chips ═══════════${accessSnippets || `
    // (open access)`}

    // ═══════════ Item chips ═══════════${itemSnippets || `
    // (any item)`}

    let item = storage_unit.withdraw_by_owner<T>(character, owner_cap, item_type_id, quantity, ctx);
    storage_unit.deposit_to_open_inventory<XAuth>(character, item, config::x_auth(), ctx);
}

/// Withdraw items from the shared open inventory into the caller's owned inventory.
public fun guarded_withdraw(
    extension_config: &ExtensionConfig,
    storage_unit: &mut StorageUnit,
    character: &Character,
    item_type_id: u64,
    quantity: u32,
    ctx: &mut TxContext,
) {${depositOnlyGuard}

    // ═══════════ Access chips ═══════════${accessSnippets || `
    // (open access)`}

    // ═══════════ Item chips ═══════════${itemSnippets || `
    // (any item)`}

    let item = storage_unit.withdraw_from_open_inventory<XAuth>(character, config::x_auth(), item_type_id, quantity, ctx);
    storage_unit.deposit_to_owned<XAuth>(character, item, config::x_auth(), ctx);
}
`;
}

// ---------------------------------------------------------------------------
// Template A: Vending Machine
// ---------------------------------------------------------------------------

function generateVendingMachineMove(selection: ChipSelection): string {
  const needsPricing = hasChip('V1', selection);
  const multiItem = hasChip('S2', selection);
  const accessSnippets = collectSnippets('access', selection);
  const pricingModifiers = collectSnippets('pricing', selection); // V2, V3, V4

  // --- Imports ---
  const coinImport = needsPricing
    ? `\nuse sui::coin::{Self, Coin};\nuse sui::sui::SUI;`
    : '';

  // --- Config structs ---
  let configStructs: string;
  if (!needsPricing) {
    configStructs = ''; // No pricing — free dispenser
  } else if (multiItem) {
    configStructs = `
public struct VendingConfig has drop, store {
    owner_address: address,
}
public struct VendingConfigKey has copy, drop, store {}

public struct ItemPriceEntry has drop, store {
    price_per_unit: u64,
}
public struct ItemPriceKey has copy, drop, store { type_id: u64 }
`;
  } else {
    configStructs = `
public struct VendingConfig has drop, store {
    price_per_unit: u64,
    owner_address: address,
}
public struct VendingConfigKey has copy, drop, store {}
`;
  }

  // --- Price reading ---
  let priceBlock: string;
  if (!needsPricing) {
    priceBlock = `
    // (no pricing — free dispenser)`;
  } else if (multiItem) {
    priceBlock = `
    // ═══════════ Pricing (multi-item) ═══════════
    assert!(extension_config.has_rule<VendingConfigKey>(VendingConfigKey {}), ENoPriceConfig);
    let vending_cfg = extension_config.borrow_rule<VendingConfigKey, VendingConfig>(VendingConfigKey {});
    assert!(extension_config.has_rule<ItemPriceKey>(ItemPriceKey { type_id: item_type_id }), ENoPriceConfig);
    let item_price = extension_config.borrow_rule<ItemPriceKey, ItemPriceEntry>(ItemPriceKey { type_id: item_type_id });
    let mut total_price = item_price.price_per_unit * (quantity as u64);`;
  } else {
    priceBlock = `
    // ═══════════ Pricing ═══════════
    assert!(extension_config.has_rule<VendingConfigKey>(VendingConfigKey {}), ENoPriceConfig);
    let vending_cfg = extension_config.borrow_rule<VendingConfigKey, VendingConfig>(VendingConfigKey {});
    let mut total_price = vending_cfg.price_per_unit * (quantity as u64);`;
  }

  // --- Revenue (payment handling) ---
  let revenueBlock: string;
  if (!needsPricing) {
    revenueBlock = '';
  } else {
    revenueBlock = `
    // ═══════════ Revenue ═══════════
    if (total_price > 0) {
        assert!(coin::value(&payment) >= total_price, EInsufficientPayment);
        let paid = coin::value(&payment);
        if (paid > total_price) {
            let change = payment.split(paid - total_price, ctx);
            transfer::public_transfer(change, ctx.sender());
        };
        transfer::public_transfer(payment, vending_cfg.owner_address);
    } else {
        transfer::public_transfer(payment, ctx.sender());
    };`;
  }

  // --- Function params ---
  const paymentParam = needsPricing ? `\n    mut payment: Coin<SUI>,` : '';

  // --- Admin functions ---
  const adminFunctions: string[] = [];
  if (needsPricing && !multiItem) {
    adminFunctions.push(`
public fun set_vending_config(
    extension_config: &mut ExtensionConfig,
    admin_cap: &AdminCap,
    price_per_unit: u64,
    owner_address: address,
) {
    extension_config.set_rule<VendingConfigKey, VendingConfig>(
        admin_cap,
        VendingConfigKey {},
        VendingConfig { price_per_unit, owner_address },
    );
}`);
  }
  if (needsPricing && multiItem) {
    adminFunctions.push(`
public fun set_vending_config(
    extension_config: &mut ExtensionConfig,
    admin_cap: &AdminCap,
    owner_address: address,
) {
    extension_config.set_rule<VendingConfigKey, VendingConfig>(
        admin_cap,
        VendingConfigKey {},
        VendingConfig { owner_address },
    );
}

public fun set_item_price(
    extension_config: &mut ExtensionConfig,
    admin_cap: &AdminCap,
    type_id: u64,
    price_per_unit: u64,
) {
    extension_config.set_rule<ItemPriceKey, ItemPriceEntry>(
        admin_cap,
        ItemPriceKey { type_id },
        ItemPriceEntry { price_per_unit },
    );
}`);
  }

  // --- Price modifier section ---
  const modifierSection = pricingModifiers
    ? `
    // ═══════════ Price modifiers ═══════════${pricingModifiers}`
    : '';

  return `/// Vending Machine — generated by EasyAssemblies.
///
/// Players pay SUI to purchase items from the SSU's main inventory.
/// Chips: [${selection.enabledChips.join(', ')}]
#[allow(unused_use, unused_variable, unused_mut_parameter)]
module smart_storage_unit_extension::vending;

use smart_storage_unit_extension::config::{Self, AdminCap, XAuth, ExtensionConfig};${coinImport}
use world::{character::Character, storage_unit::StorageUnit};

// === Errors ===
#[error(code = 0)]
const ENotAllowedTribe: vector<u8> = b"Character tribe not allowed";
#[error(code = 1)]
const ENoPriceConfig: vector<u8> = b"Missing price configuration";
#[error(code = 2)]
const EInsufficientPayment: vector<u8> = b"Insufficient payment amount";
${configStructs}
public fun buy_item(
    extension_config: &ExtensionConfig,
    storage_unit: &mut StorageUnit,
    character: &Character,${paymentParam}
    item_type_id: u64,
    quantity: u32,
    ctx: &mut TxContext,
) {
    // ═══════════ Access chips ═══════════${accessSnippets || `
    // (open access)`}
${priceBlock}${modifierSection}
${revenueBlock}
    // ═══════════ Item Delivery ═══════════
    let item = storage_unit.withdraw_item<XAuth>(character, config::x_auth(), item_type_id, quantity, ctx);
    storage_unit.deposit_to_owned<XAuth>(character, item, config::x_auth(), ctx);
}

// === Admin Functions ===
${adminFunctions.join('\n')}
`;
}

// ---------------------------------------------------------------------------
// Template B: Item Swap
// ---------------------------------------------------------------------------

function generateItemSwapMove(selection: ChipSelection): string {
  const multiPair = hasChip('W2', selection);
  const accessSnippets = collectSnippets('access', selection);

  // --- Config structs ---
  const configStructs = multiPair
    ? `
public struct SwapPair has drop, store {
    output_type_id: u64,
    ratio_num: u64,
    ratio_den: u64,
}
public struct SwapPairKey has copy, drop, store { input_type_id: u64 }
`
    : `
public struct SwapRule has drop, store {
    input_type_id: u64,
    output_type_id: u64,
    ratio_num: u64,
    ratio_den: u64,
}
public struct SwapRuleKey has copy, drop, store {}
`;

  // --- Swap logic ---
  const swapLogic = multiPair
    ? `
    // ═══════════ Swap (multi-pair) ═══════════
    assert!(extension_config.has_rule<SwapPairKey>(SwapPairKey { input_type_id }), ENoSwapRule);
    let swap_pair = extension_config.borrow_rule<SwapPairKey, SwapPair>(SwapPairKey { input_type_id });
    let output_quantity = (input_quantity as u64) * swap_pair.ratio_num / swap_pair.ratio_den;
    assert!(output_quantity > 0, EZeroOutput);
    let output_type_id = swap_pair.output_type_id;`
    : `
    // ═══════════ Swap (fixed ratio) ═══════════
    assert!(extension_config.has_rule<SwapRuleKey>(SwapRuleKey {}), ENoSwapRule);
    let swap_rule = extension_config.borrow_rule<SwapRuleKey, SwapRule>(SwapRuleKey {});
    assert!(input_type_id == swap_rule.input_type_id, EWrongInputType);
    let output_quantity = (input_quantity as u64) * swap_rule.ratio_num / swap_rule.ratio_den;
    assert!(output_quantity > 0, EZeroOutput);
    let output_type_id = swap_rule.output_type_id;`;

  // --- Admin functions ---
  const adminFn = multiPair
    ? `
public fun set_swap_pair(
    extension_config: &mut ExtensionConfig,
    admin_cap: &AdminCap,
    input_type_id: u64,
    output_type_id: u64,
    ratio_num: u64,
    ratio_den: u64,
) {
    extension_config.set_rule<SwapPairKey, SwapPair>(
        admin_cap,
        SwapPairKey { input_type_id },
        SwapPair { output_type_id, ratio_num, ratio_den },
    );
}`
    : `
public fun set_swap_rule(
    extension_config: &mut ExtensionConfig,
    admin_cap: &AdminCap,
    input_type_id: u64,
    output_type_id: u64,
    ratio_num: u64,
    ratio_den: u64,
) {
    extension_config.set_rule<SwapRuleKey, SwapRule>(
        admin_cap,
        SwapRuleKey {},
        SwapRule { input_type_id, output_type_id, ratio_num, ratio_den },
    );
}`;

  return `/// Item Swap — generated by EasyAssemblies.
///
/// Players submit items of one type and receive items of another type
/// based on a configured swap ratio.
/// Chips: [${selection.enabledChips.join(', ')}]
#[allow(unused_use, unused_variable)]
module smart_storage_unit_extension::swap;

use smart_storage_unit_extension::config::{Self, AdminCap, XAuth, ExtensionConfig};
use world::{access::OwnerCap, character::Character, storage_unit::StorageUnit};

// === Errors ===
#[error(code = 0)]
const ENotAllowedTribe: vector<u8> = b"Character tribe not allowed";
#[error(code = 1)]
const ENoSwapRule: vector<u8> = b"Missing swap rule configuration";
#[error(code = 2)]
const EWrongInputType: vector<u8> = b"Input item type does not match swap rule";
#[error(code = 3)]
const EZeroOutput: vector<u8> = b"Swap output quantity is zero";
${configStructs}
public fun swap_items<T: key>(
    extension_config: &ExtensionConfig,
    storage_unit: &mut StorageUnit,
    character: &Character,
    owner_cap: &OwnerCap<T>,
    input_type_id: u64,
    input_quantity: u32,
    ctx: &mut TxContext,
) {
    // ═══════════ Access chips ═══════════${accessSnippets || `
    // (open access)`}
${swapLogic}

    // ═══════════ Execute swap ═══════════
    let input_item = storage_unit.withdraw_by_owner<T>(character, owner_cap, input_type_id, input_quantity, ctx);
    storage_unit.deposit_item<XAuth>(character, input_item, config::x_auth(), ctx);
    let output_item = storage_unit.withdraw_item<XAuth>(character, config::x_auth(), output_type_id, (output_quantity as u32), ctx);
    storage_unit.deposit_to_owned<XAuth>(character, output_item, config::x_auth(), ctx);
}

// === Admin Functions ===
${adminFn}
`;
}

// ---------------------------------------------------------------------------
// Template D: Airdrop Hub
// ---------------------------------------------------------------------------

function generateAirdropHubMove(selection: ChipSelection): string {
  const claimOnce = hasChip('D2', selection);
  const accessSnippets = collectSnippets('access', selection);

  // When D2 (claim once) is enabled, config needs &mut for set_flag
  const configRef = claimOnce ? '&mut ExtensionConfig' : '&ExtensionConfig';

  const claimOnceStructs = claimOnce
    ? `
public struct ClaimKey has copy, drop, store { character_id: ID }
`
    : '';

  const claimCheckBlock = claimOnce
    ? `
    // [D2] Claim Once — check if already claimed
    let char_id = object::id(character);
    assert!(!config::has_rule<ClaimKey>(extension_config, ClaimKey { character_id: char_id }), EAlreadyClaimed);`
    : '';

  const claimMarkBlock = claimOnce
    ? `
    // [D2] Mark as claimed
    config::set_flag(extension_config, ClaimKey { character_id: char_id });`
    : '';

  return `/// Airdrop Hub — generated by EasyAssemblies.
///
/// SSU owner stocks items; players claim a fixed quantity per visit.
/// Chips: [${selection.enabledChips.join(', ')}]
#[allow(unused_use, unused_variable)]
module smart_storage_unit_extension::airdrop;

use smart_storage_unit_extension::config::{Self, AdminCap, XAuth, ExtensionConfig};
use world::{character::Character, storage_unit::StorageUnit};

// === Errors ===
#[error(code = 0)]
const ENotAllowedTribe: vector<u8> = b"Character tribe not allowed";
#[error(code = 1)]
const ENoAirdropConfig: vector<u8> = b"Missing airdrop configuration";
#[error(code = 2)]
const EAlreadyClaimed: vector<u8> = b"Airdrop already claimed by this character";

public struct AirdropConfig has drop, store {
    item_type_id: u64,
    quantity: u32,
}
public struct AirdropConfigKey has copy, drop, store {}
${claimOnceStructs}
public fun claim_airdrop(
    extension_config: ${configRef},
    storage_unit: &mut StorageUnit,
    character: &Character,
    ctx: &mut TxContext,
) {
    // ═══════════ Access chips ═══════════${accessSnippets || `
    // (open access)`}
${claimCheckBlock}
    // ═══════════ Airdrop ═══════════
    assert!(extension_config.has_rule<AirdropConfigKey>(AirdropConfigKey {}), ENoAirdropConfig);
    let airdrop_cfg = extension_config.borrow_rule<AirdropConfigKey, AirdropConfig>(AirdropConfigKey {});
    let airdrop_type_id = airdrop_cfg.item_type_id;
    let airdrop_quantity = airdrop_cfg.quantity;

    let item = storage_unit.withdraw_item<XAuth>(character, config::x_auth(), airdrop_type_id, airdrop_quantity, ctx);
    storage_unit.deposit_to_owned<XAuth>(character, item, config::x_auth(), ctx);
${claimMarkBlock}
}

// === Admin Functions ===
public fun set_airdrop_config(
    extension_config: &mut ExtensionConfig,
    admin_cap: &AdminCap,
    item_type_id: u64,
    quantity: u32,
) {
    extension_config.set_rule<AirdropConfigKey, AirdropConfig>(
        admin_cap,
        AirdropConfigKey {},
        AirdropConfig { item_type_id, quantity },
    );
}
`;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export type SSUTemplateTag =
  | 'vending_machine'
  | 'item_swap'
  | 'gated_locker'
  | 'airdrop_hub'
  | 'open_storage';

export interface SSUGeneratorInput {
  templateTag: SSUTemplateTag;
  moduleName?: string;
  selection: ChipSelection;
}

const mainFileGenerators: Record<
  SSUTemplateTag,
  (selection: ChipSelection) => { filename: string; content: string }
> = {
  open_storage:     () => ({ filename: 'sources/open_storage.move', content: generateOpenStorageMove() }),
  gated_locker:     s  => ({ filename: 'sources/locker.move', content: generateGatedLockerMove(s) }),
  vending_machine:  s  => ({ filename: 'sources/vending.move', content: generateVendingMachineMove(s) }),
  item_swap:        s  => ({ filename: 'sources/swap.move', content: generateItemSwapMove(s) }),
  airdrop_hub:      s  => ({ filename: 'sources/airdrop.move', content: generateAirdropHubMove(s) }),
};

export function generateSSUFiles(input: SSUGeneratorInput): FileMap {
  const moduleName = input.moduleName || DEFAULT_MODULE;
  const gen = mainFileGenerators[input.templateTag];
  const main = gen(input.selection);

  return {
    'Move.toml': generateMoveToml(moduleName),
    'sources/config.move': replaceModuleName(generateConfigMove(), moduleName),
    [main.filename]: replaceModuleName(main.content, moduleName),
  };
}
