/**
 * Gate code generator — assembles Move source files from template + chip selections.
 *
 * Unlike Turret (1 template, many chip combos), Gate has multiple templates
 * with structurally different code. The generator dispatches on `templateTag`
 * to pick the right skeleton, then injects chip snippets into marked regions.
 *
 * Produces:
 *   Move.toml              — package manifest
 *   sources/config.move    — shared ExtensionConfig + AdminCap + XAuth (all templates)
 *   sources/<main>.move    — template-specific main module with chip code injected
 */

import type { FileMap } from '../types';
import type { ChipSelection } from '../chip-types';
import { GATE_CHIPS } from './chips';

const DEFAULT_MODULE = 'smart_gate_extension';

function replaceModuleName(source: string, moduleName: string): string {
  if (moduleName === DEFAULT_MODULE) return source;
  return source.replaceAll(DEFAULT_MODULE, moduleName);
}

function collectSnippets(
  category: string,
  selection: ChipSelection,
): string {
  const enabled = GATE_CHIPS.filter(
    c => c.category === category && selection.enabledChips.includes(c.id),
  );
  if (enabled.length === 0) return '';
  return enabled
    .map(chip => {
      const params = selection.chipConfigs[chip.id];
      return chip.codeSnippet(params);
    })
    .join('\n');
}

function hasChip(id: string, selection: ChipSelection): boolean {
  return selection.enabledChips.includes(id);
}

// ---------------------------------------------------------------------------
// Move.toml (shared by all Gate templates)
// ---------------------------------------------------------------------------

function generateMoveToml(moduleName: string): string {
  return `[package]
name = "${moduleName}"
edition = "2024"

[dependencies]
world = { git = "https://github.com/evefrontier/world-contracts.git", subdir = "contracts/world", rev = "v0.0.21" }

[environments]
testnet = "4c78adac"
testnet_internal = "4c78adac"
testnet_utopia = "4c78adac"
testnet_stillness = "4c78adac"
`;
}

// ---------------------------------------------------------------------------
// sources/config.move (shared by all Gate templates)
// ---------------------------------------------------------------------------

function generateConfigMove(): string {
  return `/// Shared configuration for gate extensions — generated by EasyAssemblies.
module smart_gate_extension::config;

use sui::dynamic_field as df;

public struct ExtensionConfig has key {
    id: UID,
}

public struct AdminCap has key, store {
    id: UID,
}

public struct XAuth has drop {}

fun init(ctx: &mut TxContext) {
    let admin_cap = AdminCap { id: object::new(ctx) };
    transfer::transfer(admin_cap, ctx.sender());

    let config = ExtensionConfig { id: object::new(ctx) };
    transfer::share_object(config);
}

public fun has_rule<K: copy + drop + store>(config: &ExtensionConfig, key: K): bool {
    df::exists_(&config.id, key)
}

public fun borrow_rule<K: copy + drop + store, V: store>(config: &ExtensionConfig, key: K): &V {
    df::borrow(&config.id, key)
}

public fun borrow_rule_mut<K: copy + drop + store, V: store>(
    config: &mut ExtensionConfig,
    _: &AdminCap,
    key: K,
): &mut V {
    df::borrow_mut(&mut config.id, key)
}

public fun add_rule<K: copy + drop + store, V: store>(
    config: &mut ExtensionConfig,
    _: &AdminCap,
    key: K,
    value: V,
) {
    df::add(&mut config.id, key, value);
}

public fun set_rule<K: copy + drop + store, V: store + drop>(
    config: &mut ExtensionConfig,
    _: &AdminCap,
    key: K,
    value: V,
) {
    if (df::exists_(&config.id, copy key)) {
        let _old: V = df::remove(&mut config.id, copy key);
    };
    df::add(&mut config.id, key, value);
}

public fun remove_rule<K: copy + drop + store, V: store>(
    config: &mut ExtensionConfig,
    _: &AdminCap,
    key: K,
): V {
    df::remove(&mut config.id, key)
}

public(package) fun x_auth(): XAuth {
    XAuth {}
}
`;
}

// ---------------------------------------------------------------------------
// Template A: Tribe Permit
// ---------------------------------------------------------------------------

function generateTribePermitMove(selection: ChipSelection): string {
  const accessSnippets = collectSnippets('access', selection);

  const needsTribeConfig = hasChip('A1', selection);
  const tribeConfigTypes = needsTribeConfig
    ? `
public struct TribeConfig has drop, store {
    tribe: u32,
    expiry_duration_ms: u64,
}

public struct TribeConfigKey has copy, drop, store {}
`
    : '';

  const adminFunctions = needsTribeConfig
    ? `
// === Admin Functions ===
public fun set_tribe_config(
    extension_config: &mut ExtensionConfig,
    admin_cap: &AdminCap,
    tribe: u32,
    expiry_duration_ms: u64,
) {
    extension_config.set_rule<TribeConfigKey, TribeConfig>(
        admin_cap,
        TribeConfigKey {},
        TribeConfig { tribe, expiry_duration_ms },
    );
}
`
    : '';

  const expirySource = needsTribeConfig
    ? `let expiry_ms = tribe_cfg.expiry_duration_ms;`
    : `let expiry_ms: u64 = 3_600_000;`;

  return `/// Tribe Permit Gate — generated by EasyAssemblies.
///
/// Chips: [${selection.enabledChips.join(', ')}]
#[allow(unused_use)]
module smart_gate_extension::tribe_permit;

use smart_gate_extension::config::{Self, AdminCap, XAuth, ExtensionConfig};
use sui::clock::Clock;
use world::{character::Character, gate::{Self, Gate}};

// === Errors ===
#[error(code = 0)]
const ENotAllowedTribe: vector<u8> = b"Character tribe not allowed";
#[error(code = 1)]
const ENoTribeConfig: vector<u8> = b"Missing TribeConfig on ExtensionConfig";
#[error(code = 2)]
const EExpiryOverflow: vector<u8> = b"Expiry timestamp overflow";
#[error(code = 3)]
const EBlockedTribe: vector<u8> = b"Character tribe is blocked";
${tribeConfigTypes}
public fun issue_jump_permit(
    extension_config: &ExtensionConfig,
    source_gate: &Gate,
    destination_gate: &Gate,
    character: &Character,
    clock: &Clock,
    ctx: &mut TxContext,
) {
    // ═══════════ Access chips ═══════════${accessSnippets || `
    // (none selected)`}

    // ═══════════ Issue permit ═══════════
    ${expirySource}
    let ts = clock.timestamp_ms();
    assert!(ts <= (0xFFFFFFFFFFFFFFFFu64 - expiry_ms), EExpiryOverflow);
    let expires_at_timestamp_ms = ts + expiry_ms;
    gate::issue_jump_permit<XAuth>(
        source_gate,
        destination_gate,
        character,
        config::x_auth(),
        expires_at_timestamp_ms,
        ctx,
    );
}
${adminFunctions}`;
}

// ---------------------------------------------------------------------------
// Template B: Toll Gate
// ---------------------------------------------------------------------------

function generateTollGateMove(selection: ChipSelection): string {
  const paymentSnippets = collectSnippets('payment', selection);
  const revenueSnippets = collectSnippets('revenue', selection);

  return `/// Toll Gate — generated by EasyAssemblies.
///
/// Chips: [${selection.enabledChips.join(', ')}]
#[allow(unused_use, unused_variable)]
module smart_gate_extension::toll_gate;

use smart_gate_extension::config::{Self, AdminCap, XAuth, ExtensionConfig};
use sui::clock::Clock;
use sui::coin::{Self, Coin};
use sui::sui::SUI;
use world::{character::Character, gate::{Self, Gate}};

// === Errors ===
#[error(code = 0)]
const ENoTollConfig: vector<u8> = b"Missing TollConfig on ExtensionConfig";
#[error(code = 1)]
const EInsufficientPayment: vector<u8> = b"Insufficient payment amount";
#[error(code = 2)]
const EExpiryOverflow: vector<u8> = b"Expiry timestamp overflow";

public struct TollConfig has drop, store {
    price: u64,
    owner_address: address,
    expiry_duration_ms: u64,
}

public struct TollConfigKey has copy, drop, store {}

public fun buy_pass(
    extension_config: &ExtensionConfig,
    source_gate: &Gate,
    destination_gate: &Gate,
    character: &Character,
    mut payment: Coin<SUI>,
    clock: &Clock,
    ctx: &mut TxContext,
) {
    // ═══════════ Payment chips ═══════════${paymentSnippets || `
    // (none selected)`}

    // ═══════════ Revenue chips ═══════════${revenueSnippets || `
    // (none selected)`}

    // ═══════════ Issue permit ═══════════
    let expiry_ms = toll_cfg.expiry_duration_ms;
    let ts = clock.timestamp_ms();
    assert!(ts <= (0xFFFFFFFFFFFFFFFFu64 - expiry_ms), EExpiryOverflow);
    let expires_at_timestamp_ms = ts + expiry_ms;
    gate::issue_jump_permit<XAuth>(
        source_gate,
        destination_gate,
        character,
        config::x_auth(),
        expires_at_timestamp_ms,
        ctx,
    );
}

// === Admin Functions ===
public fun set_toll_config(
    extension_config: &mut ExtensionConfig,
    admin_cap: &AdminCap,
    price: u64,
    owner_address: address,
    expiry_duration_ms: u64,
) {
    extension_config.set_rule<TollConfigKey, TollConfig>(
        admin_cap,
        TollConfigKey {},
        TollConfig { price, owner_address, expiry_duration_ms },
    );
}
`;
}

// ---------------------------------------------------------------------------
// Template C: Bounty Gate
// ---------------------------------------------------------------------------

function generateBountyGateMove(selection: ChipSelection): string {
  const itemSnippets = collectSnippets('item', selection);

  return `/// Bounty Gate — generated by EasyAssemblies.
///
/// Chips: [${selection.enabledChips.join(', ')}]
#[allow(unused_use, unused_variable)]
module smart_gate_extension::bounty_gate;

use smart_gate_extension::config::{Self, AdminCap, XAuth, ExtensionConfig};
use sui::clock::Clock;
use world::{
    access::OwnerCap,
    character::Character,
    gate::{Self, Gate},
    storage_unit::StorageUnit,
};

// === Errors ===
#[error(code = 0)]
const ENoBountyConfig: vector<u8> = b"Missing BountyConfig on ExtensionConfig";
#[error(code = 1)]
const EItemTypeMismatch: vector<u8> = b"Item type mismatch";
#[error(code = 2)]
const EItemTypeNotAccepted: vector<u8> = b"Item type not accepted";
#[error(code = 3)]
const EInsufficientQuantity: vector<u8> = b"Insufficient item quantity";
#[error(code = 4)]
const EExpiryOverflow: vector<u8> = b"Expiry timestamp overflow";

public struct BountyConfig has drop, store {
    bounty_type_id: u64,
    expiry_duration_ms: u64,
}

public struct BountyConfigKey has copy, drop, store {}

public fun collect_bounty<T: key>(
    extension_config: &ExtensionConfig,
    storage_unit: &mut StorageUnit,
    source_gate: &Gate,
    destination_gate: &Gate,
    character: &Character,
    player_inventory_owner_cap: &OwnerCap<T>,
    item_type_id: u64,
    quantity: u32,
    clock: &Clock,
    ctx: &mut TxContext,
) {
    let corpse = storage_unit.withdraw_by_owner<T>(
        character,
        player_inventory_owner_cap,
        item_type_id,
        quantity,
        ctx,
    );

    // ═══════════ Item chips ═══════════${itemSnippets || `
    // (none selected)`}

    storage_unit.deposit_item<XAuth>(
        character,
        corpse,
        config::x_auth(),
        ctx,
    );

    // ═══════════ Issue permit ═══════════
    let bounty_cfg = extension_config.borrow_rule<BountyConfigKey, BountyConfig>(BountyConfigKey {});
    let expiry_ms = bounty_cfg.expiry_duration_ms;
    let ts = clock.timestamp_ms();
    assert!(ts <= (0xFFFFFFFFFFFFFFFFu64 - expiry_ms), EExpiryOverflow);
    let expires_at_timestamp_ms = ts + expiry_ms;
    gate::issue_jump_permit<XAuth>(
        source_gate,
        destination_gate,
        character,
        config::x_auth(),
        expires_at_timestamp_ms,
        ctx,
    );
}

// === Admin Functions ===
public fun set_bounty_config(
    extension_config: &mut ExtensionConfig,
    admin_cap: &AdminCap,
    bounty_type_id: u64,
    expiry_duration_ms: u64,
) {
    extension_config.set_rule<BountyConfigKey, BountyConfig>(
        admin_cap,
        BountyConfigKey {},
        BountyConfig { bounty_type_id, expiry_duration_ms },
    );
}
`;
}

// ---------------------------------------------------------------------------
// Template D: Open Permit
// ---------------------------------------------------------------------------

function generateOpenPermitMove(selection: ChipSelection): string {
  return `/// Open Permit Gate — generated by EasyAssemblies.
///
/// Anyone can request a permit. No access restrictions.
/// Chips: [${selection.enabledChips.join(', ')}]
#[allow(unused_use)]
module smart_gate_extension::open_permit;

use smart_gate_extension::config::{Self, XAuth};
use sui::clock::Clock;
use world::{character::Character, gate::{Self, Gate}};

// === Errors ===
#[error(code = 0)]
const EExpiryOverflow: vector<u8> = b"Expiry timestamp overflow";

const PERMIT_DURATION_MS: u64 = 3_600_000;

public fun request_permit(
    source_gate: &Gate,
    destination_gate: &Gate,
    character: &Character,
    clock: &Clock,
    ctx: &mut TxContext,
) {
    let ts = clock.timestamp_ms();
    assert!(ts <= (0xFFFFFFFFFFFFFFFFu64 - PERMIT_DURATION_MS), EExpiryOverflow);
    let expires_at = ts + PERMIT_DURATION_MS;
    gate::issue_jump_permit<XAuth>(
        source_gate,
        destination_gate,
        character,
        config::x_auth(),
        expires_at,
        ctx,
    );
}
`;
}

// ---------------------------------------------------------------------------
// Template E: Multi-Rule Gate
// ---------------------------------------------------------------------------

function generateMultiRuleMove(selection: ChipSelection): string {
  const accessSnippets = collectSnippets('access', selection);
  const paymentSnippets = collectSnippets('payment', selection);
  const revenueSnippets = collectSnippets('revenue', selection);

  const needsPayment = hasChip('P1', selection);
  const needsTribeConfig = hasChip('A1', selection);

  const tribeConfigTypes = needsTribeConfig
    ? `
public struct TribeConfig has drop, store {
    tribe: u32,
}

public struct TribeConfigKey has copy, drop, store {}
`
    : '';

  const tollConfigTypes = needsPayment
    ? `
public struct TollConfig has drop, store {
    price: u64,
    owner_address: address,
}

public struct TollConfigKey has copy, drop, store {}
`
    : '';

  const paymentParam = needsPayment ? `\n    mut payment: Coin<SUI>,` : '';
  const coinImport = needsPayment
    ? `\nuse sui::coin::{Self, Coin};\nuse sui::sui::SUI;`
    : '';

  const adminFunctions: string[] = [];
  if (needsTribeConfig) {
    adminFunctions.push(`
public fun set_tribe_config(
    extension_config: &mut ExtensionConfig,
    admin_cap: &AdminCap,
    tribe: u32,
) {
    extension_config.set_rule<TribeConfigKey, TribeConfig>(
        admin_cap,
        TribeConfigKey {},
        TribeConfig { tribe },
    );
}`);
  }
  if (needsPayment) {
    adminFunctions.push(`
public fun set_toll_config(
    extension_config: &mut ExtensionConfig,
    admin_cap: &AdminCap,
    price: u64,
    owner_address: address,
) {
    extension_config.set_rule<TollConfigKey, TollConfig>(
        admin_cap,
        TollConfigKey {},
        TollConfig { price, owner_address },
    );
}`);
  }

  return `/// Multi-Rule Gate — generated by EasyAssemblies.
///
/// Combines access control and payment rules in a single gate.
/// Chips: [${selection.enabledChips.join(', ')}]
#[allow(unused_use, unused_variable)]
module smart_gate_extension::multi_rule;

use smart_gate_extension::config::{Self, AdminCap, XAuth, ExtensionConfig};
use sui::clock::Clock;${coinImport}
use world::{character::Character, gate::{Self, Gate}};

// === Errors ===
#[error(code = 0)]
const ENotAllowedTribe: vector<u8> = b"Character tribe not allowed";
#[error(code = 1)]
const ENoTribeConfig: vector<u8> = b"Missing TribeConfig on ExtensionConfig";
#[error(code = 2)]
const EBlockedTribe: vector<u8> = b"Character tribe is blocked";
#[error(code = 3)]
const ENoTollConfig: vector<u8> = b"Missing TollConfig on ExtensionConfig";
#[error(code = 4)]
const EInsufficientPayment: vector<u8> = b"Insufficient payment amount";
#[error(code = 5)]
const EExpiryOverflow: vector<u8> = b"Expiry timestamp overflow";

public struct MultiRuleConfig has drop, store {
    expiry_duration_ms: u64,
}

public struct MultiRuleConfigKey has copy, drop, store {}
${tribeConfigTypes}${tollConfigTypes}
public fun issue_jump_permit(
    extension_config: &ExtensionConfig,
    source_gate: &Gate,
    destination_gate: &Gate,
    character: &Character,${paymentParam}
    clock: &Clock,
    ctx: &mut TxContext,
) {
    // ═══════════ Access chips ═══════════${accessSnippets || `
    // (none selected)`}

    // ═══════════ Payment chips ═══════════${paymentSnippets || `
    // (none selected)`}

    // ═══════════ Revenue chips ═══════════${revenueSnippets || `
    // (none selected)`}

    // ═══════════ Issue permit ═══════════
    assert!(extension_config.has_rule<MultiRuleConfigKey>(MultiRuleConfigKey {}), EExpiryOverflow);
    let mr_cfg = extension_config.borrow_rule<MultiRuleConfigKey, MultiRuleConfig>(MultiRuleConfigKey {});
    let expiry_ms = mr_cfg.expiry_duration_ms;
    let ts = clock.timestamp_ms();
    assert!(ts <= (0xFFFFFFFFFFFFFFFFu64 - expiry_ms), EExpiryOverflow);
    let expires_at_timestamp_ms = ts + expiry_ms;
    gate::issue_jump_permit<XAuth>(
        source_gate,
        destination_gate,
        character,
        config::x_auth(),
        expires_at_timestamp_ms,
        ctx,
    );
}

// === Admin Functions ===
public fun set_multi_rule_config(
    extension_config: &mut ExtensionConfig,
    admin_cap: &AdminCap,
    expiry_duration_ms: u64,
) {
    extension_config.set_rule<MultiRuleConfigKey, MultiRuleConfig>(
        admin_cap,
        MultiRuleConfigKey {},
        MultiRuleConfig { expiry_duration_ms },
    );
}
${adminFunctions.join('\n')}
`;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export type GateTemplateTag =
  | 'tribe_permit'
  | 'toll_gate'
  | 'bounty_gate'
  | 'open_permit'
  | 'multi_rule';

export interface GateGeneratorInput {
  templateTag: GateTemplateTag;
  moduleName?: string;
  selection: ChipSelection;
}

const mainFileGenerators: Record<
  GateTemplateTag,
  (selection: ChipSelection) => { filename: string; content: string }
> = {
  tribe_permit: (s) => ({ filename: 'sources/tribe_permit.move', content: generateTribePermitMove(s) }),
  toll_gate:    (s) => ({ filename: 'sources/toll_gate.move', content: generateTollGateMove(s) }),
  bounty_gate:  (s) => ({ filename: 'sources/bounty_gate.move', content: generateBountyGateMove(s) }),
  open_permit:  (s) => ({ filename: 'sources/open_permit.move', content: generateOpenPermitMove(s) }),
  multi_rule:   (s) => ({ filename: 'sources/multi_rule.move', content: generateMultiRuleMove(s) }),
};

export function generateGateFiles(input: GateGeneratorInput): FileMap {
  const moduleName = input.moduleName || DEFAULT_MODULE;
  const gen = mainFileGenerators[input.templateTag];
  const main = gen(input.selection);

  const files: FileMap = {
    'Move.toml': generateMoveToml(moduleName),
    'sources/config.move': replaceModuleName(generateConfigMove(), moduleName),
    [main.filename]: replaceModuleName(main.content, moduleName),
  };

  return files;
}
