/// Turret Targeting Extension — generated by EasyAssemblies.
///
/// Chips: [E1, E2, E3, W1, W2]
module smart_turret_extension::turret;

use sui::bcs;
use world::{
    character::{Self, Character},
    turret::{Self, Turret, OnlineReceipt},
};

#[error(code = 0)]
const EInvalidReceipt: vector<u8> = b"OnlineReceipt does not match turret";

// BehaviourChangeReason discriminants (via BCS tag byte)
const ENTERED: u8 = 1;
const STARTED_ATTACK: u8 = 2;
const STOPPED_ATTACK: u8 = 3;

fun behaviour_to_u8(reason: turret::BehaviourChangeReason): u8 {
    let bytes = bcs::to_bytes(&reason);
    bytes[0]
}

public struct TurretAuth has drop {}

public fun get_target_priority_list(
    turret: &Turret,
    owner_character: &Character,
    target_candidate_list: vector<u8>,
    receipt: OnlineReceipt,
): vector<u8> {
    assert!(receipt.turret_id() == object::id(turret), EInvalidReceipt);

    let candidates = turret::unpack_candidate_list(target_candidate_list);
    let owner_character_id = character::key(owner_character).item_id() as u32;
    let owner_tribe = character::tribe(owner_character);

    let mut return_list = vector::empty<turret::ReturnTargetPriorityList>();

    let mut i = 0u64;
    let len = candidates.length();
    while (i < len) {
        let candidate = &candidates[i];
        let mut weight = turret::priority_weight(candidate);
        let mut excluded = false;

        // ═══════════ Exclude chips ═══════════
        // [E1] Friendly Fire Protection
        if (turret::character_tribe(candidate) == owner_tribe && !turret::is_aggressor(candidate)) {
            excluded = true;
        };

        // [E2] Owner Protection
        if (turret::character_id(candidate) != 0 && turret::character_id(candidate) == owner_character_id) {
            excluded = true;
        };

        // [E3] Ceasefire Detection
        if (behaviour_to_u8(turret::behaviour_change(candidate)) == STOPPED_ATTACK) {
            excluded = true;
        };

        if (!excluded) {
            // ═══════════ Weight chips ═══════════
            // [W1] Aggressor Priority
            if (behaviour_to_u8(turret::behaviour_change(candidate)) == STARTED_ATTACK) {
                weight = weight + 10000;
            };

            // [W2] Proximity Alert
            if (behaviour_to_u8(turret::behaviour_change(candidate)) == ENTERED) {
                if (turret::character_tribe(candidate) != owner_tribe || turret::is_aggressor(candidate)) {
                    weight = weight + 1000;
                };
            };

            return_list.push_back(
                turret::new_return_target_priority_list(turret::item_id(candidate), weight),
            );
        };

        i = i + 1;
    };

    turret::destroy_online_receipt(receipt, TurretAuth {});
    bcs::to_bytes(&return_list)
}
